Repository hmcts/cnp-plum-frontend, pull requests merged in 2023-04, with the labels that each got.

#240 DTSPO-11734 - renovate - add schema
  .github/renovate.json
Labels: chore

#243 Try upgrading to node 18
  .nvmrc
  package.json
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-243

#244 upgrade docker image to v18
  Dockerfile
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-244

#246 upgrade to node 18
  Dockerfile
  acb.tpl.yaml
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-246

#251 Upgrade chart-nodejs to get workload identity
  charts/plum-frontend/Chart.yaml
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-251
