Repository hmcts/cnp-plum-frontend, pull requests merged in 2023-10, with the labels that each got.

#520 Upgrade to use wl identity
  charts/plum-frontend/Chart.yaml
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-520

#530 Revert to Ubuntu 20.04
  .github/workflows/checks.yml
  sorted-yarn-audit-issues
  yarn-audit-known-issues
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-530

#535 DTSPO-15411 - Update suppressions
  yarn-audit-known-issues
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-535
