Repository hmcts/cnp-plum-frontend, pull requests merged in 2023-03, with the labels that each got.

#210 DTSPO-7637 - Remove slackChannel param
  Jenkinsfile_pipeline_test
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-210

#223 Ignore coverage on app dir
  sonar-project.properties
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-223

#235 DTSPO-11734 - use default branch for renovate config
  .github/renovate.json
Labels: ns:cnp, prd:plum, rel:plum-frontend-pr-235

#236 Renovate - use global presets
  .github/renovate.json
Labels: ns:cnp, prd:plum, chore, rel:plum-frontend-pr-236
